# Generated by Django 3.0.5 on 2020-04-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Party', max_length=200)),
                ('description', models.CharField(default='Party', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Party', max_length=200)),
                ('url', models.CharField(default='https://moi-portal.ru/upload/iblock/d9e/d9e5efcd756fe6681d27e921f9f2599a.jpg', max_length=500)),
                ('description', models.CharField(default='Party', max_length=1000)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
